spring.application.name: gather-platform
server.port: 82

logging.level.root: INFO
##下个版本修正为使用spring.data.*默认配置项
gs.es.need: true
##不用ES是没什么意义的，所以我认为这个参数是多余的
gs.es.host: ${ES_HOST:localhost}
gs.es.port: ${ES_PORT:9300}
gs.es.cluster.name: ${CLUSTER_NAME:docker-cluster}
gs.redis.need: true
gs.redis.host: ${REDIS_HOST:localhost}
gs.redis.port: ${REDIS_PORT:10000}
gs.redis.webpage.channel.name: webpage
gs.max.http.downloader.length: 1048576
gs.ajax.downloader: http://localhost:7788/

#spring.mvc.view.prefix: /pages/
#spring.mvc.view.suffix: .jsp

spring.thymeleaf.enalbed: true
spring.thymeleaf.mode: HTML5
spring.thymeleaf.suffix: .html
spring.thymeleaf.cache: false

